### ISSUE TITLE
如何实现后退缓存，前进或者平级路由清除缓存

### ISSUE THREAD

**Issue by LuoQaxa** [GoodLuckAlien/react-keepalive-router#12]
问题：如何判断路由是前进还是后退实现前进刷新，后退不刷新。

场景：如A-B-C，A,B为列表页面从C页面返回时需要缓存，但是从A-B时,B需要更新

**Comment by GoodLuckAlien** [comment]
> 问题：如何判断路由是前进还是后退实现前进刷新，后退不刷新。
> 
> 场景：如A-B-C，A,B为列表页面从C页面返回时需要缓存，但是从A-B时,B需要更新

这个方式实际很好实现，就是从 A 进入到 B 的时候，清除缓存就可以了。
