### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by huyu456** [GoodLuckAlien/react-keepalive-router#3]
希望可以增加保存滚动位置的功能
是否可以将快弃用的钩子修改为UNSAFE的形式，我控制台总是报componentWillReceiveProps的警告

**Comment by GoodLuckAlien** [comment]
> 希望可以增加保存滚动位置的功能
> 是否可以将快弃用的钩子修改为UNSAFE的形式，我控制台总是报componentWillReceiveProps的警告

你好，非常感谢你提出宝贵的建议，我会尽快修复问题，并进行功能优化。发布最新版本，我会第一时间通知你🌹🌹🌹

**Comment by huyu456** [comment]
> > 希望可以增加保存滚动位置的功能
> > 是否可以将快弃用的钩子修改为UNSAFE的形式，我控制台总是报componentWillReceiveProps的警告
> 
> 你好，非常感谢你提出宝贵的建议，我会尽快修复问题，并进行功能优化。发布最新版本，我会第一时间通知你🌹🌹🌹



> > 希望可以增加保存滚动位置的功能
> > 是否可以将快弃用的钩子修改为UNSAFE的形式，我控制台总是报componentWillReceiveProps的警告
> 
> 你好，非常感谢你提出宝贵的建议，我会尽快修复问题，并进行功能优化。发布最新版本，我会第一时间通知你🌹🌹🌹

**Comment by huyu456** [comment]
期待，加油

**Comment by huyu456** [comment]
> 你好，非常感谢你提出宝贵的建议，我会尽快修复问题，并进行功能优化。发布最新版本，我会第一时间通知你🌹🌹🌹
期待，加油

**Comment by GoodLuckAlien** [comment]
> 希望可以增加保存滚动位置的功能
> 是否可以将快弃用的钩子修改为UNSAFE的形式，我控制台总是报componentWillReceiveProps的警告

`react-keepalive-router` 发布1.1.2版本  
更改如下：
  1  增加页面生命周期  激活状态`actived`钩子 缓存状态钩子`unActived`。
     
  2  支持缓存`scroll`滚动条位置。

  3 `keepaliveRoute`,`UNSAFE_componentWillReceiveProps` 代替 `componentWillReceiveProps`。

 4  提供了完整的`demo`项目。`example`文件夹下。

详情参考： https://github.com/GoodLuckAlien/react-keepalive-router

**Comment by huyu456** [comment]
> > 希望可以增加保存滚动位置的功能
> > 是否可以将快弃用的钩子修改为UNSAFE的形式，我控制台总是报componentWillReceiveProps的警告
> 
> `react-keepalive-router`发布1.1.2版本
> 更改如下：
> 1增加页面生命周期激活状态`actived`钩子缓存状态钩子`unActived`。
> 
> 2支持缓存`scroll`滚动条位置。
> 
> 3 `keepaliveRoute`，`UNSAFE_componentWillReceiveProps`代替`componentWillReceiveProps`。
> 
> 4提供了完整的`demo`项目。`example`文件夹下。
> 
> 详情参考：[https](https://github.com/GoodLuckAlien/react-keepalive-router) : [//github.com/GoodLuckAlien/react-keepalive-router](https://github.com/GoodLuckAlien/react-keepalive-router)

厉害了👍

**Comment by huyu456** [comment]
> > 希望可以增加保存滚动位置的功能
> > 是否可以将快弃用的钩子修改为UNSAFE的形式，我控制台总是报componentWillReceiveProps的警告
> 
> `react-keepalive-router`发布1.1.2版本
> 更改如下：
> 1增加页面生命周期激活状态`actived`钩子缓存状态钩子`unActived`。
> 
> 2支持缓存`scroll`滚动条位置。
> 
> 3 `keepaliveRoute`，`UNSAFE_componentWillReceiveProps`代替`componentWillReceiveProps`。
> 
> 4提供了完整的`demo`项目。`example`文件夹下。
> 
> 详情参考：[https](https://github.com/GoodLuckAlien/react-keepalive-router) : [//github.com/GoodLuckAlien/react-keepalive-router](https://github.com/GoodLuckAlien/react-keepalive-router)

似乎多个页面使用scroll会出现干扰的情况

**Comment by GoodLuckAlien** [comment]
> > > 希望可以增加保存滚动位置的功能
> > > 是否可以将快弃用的钩子修改为UNSAFE的形式，我控制台总是报componentWillReceiveProps的警告
> > 
> > 
> > `react-keepalive-router`发布1.1.2版本
> > 更改如下：
> > 1增加页面生命周期激活状态`actived`钩子缓存状态钩子`unActived`。
> > 2支持缓存`scroll`滚动条位置。
> > 3 `keepaliveRoute`，`UNSAFE_componentWillReceiveProps`代替`componentWillReceiveProps`。
> > 4提供了完整的`demo`项目。`example`文件夹下。
> > 详情参考：[https](https://github.com/GoodLuckAlien/react-keepalive-router) : [//github.com/GoodLuckAlien/react-keepalive-router](https://github.com/GoodLuckAlien/react-keepalive-router)
> 
> 似乎多个页面使用scroll会出现干扰的情况

好的 真的很感谢您，稍后我会针对这个情况进行问题的排查与修复。
