### ISSUE TITLE
提供完整的 demo

### ISSUE THREAD

**Issue by chnliquan** [GoodLuckAlien/react-keepalive-router#4]
请问可以给一个完成的可以跑起来的示例吗？你这个 KeepAliveRoute 缓存的是真实的 DOM，按照 README 里面的 gif，切换回去数字还是 8，如果在点击 add，这个数字会是 1 还是 9？

**Comment by GoodLuckAlien** [comment]
您好，首先回答问题，肯定是9，功能主要是让整个`fiber`树存活，包括状态 ,稍后我会写几个应用场景的`demo`，上传到项目的`example`文件夹下面（目前还没有），非常感谢您的宝贵建议。

**Comment by GoodLuckAlien** [comment]
> 请问可以给一个完成的可以跑起来的示例吗？你这个 KeepAliveRoute 缓存的是真实的 DOM，按照 README 里面的 gif，切换回去数字还是 8，如果在点击 add，这个数字会是 1 还是 9？

您好，首先回答问题，肯定是9，功能主要是让整个fiber树存活，包括状态 ,稍后我会写几个应用场景的demo，上传到项目的example文件夹下面（目前还没有），非常感谢您的宝贵建议。

**Comment by GoodLuckAlien** [comment]
> 请问可以给一个完成的可以跑起来的示例吗？你这个 KeepAliveRoute 缓存的是真实的 DOM，按照 README 里面的 gif，切换回去数字还是 8，如果在点击 add，这个数字会是 1 还是 9？

`react-keepalive-router` 发布1.1.2版本  
更改如下：
  1  增加页面生命周期  激活状态`actived`钩子 缓存状态钩子`unActived`。
     
  2  支持缓存`scroll`滚动条位置。

  3 `keepaliveRoute`,`UNSAFE_componentWillReceiveProps` 代替 `componentWillReceiveProps`。

 4  提供了完整的`demo`项目。`example`文件夹下。

详情参考： https://github.com/GoodLuckAlien/react-keepalive-router

**Comment by Aurora567** [comment]
demo跑不起来
