### ISSUE TITLE
函数组件中页面表现与react的实际状态不一致

### ISSUE THREAD

**Issue by mouse-007** [GoodLuckAlien/react-keepalive-router#9]
函数组件中，页面的状态与组件实际状态不一致，页面更像是一个快照，函数组件中的state都被初始化了。
函数组件有一个输入框 值为5，再次进入时页面也显示5，但是打印出来的却是初始值。感觉真实dom与react虚拟dom不一致。

**Comment by GoodLuckAlien** [comment]
非常感谢您的宝贵意见，这个是我们接下来重点解决的方向，将对 DOM 层面， state 层面均作缓存处理

**Comment by GoodLuckAlien** [comment]
> 函数组件中，页面的状态与组件实际状态不一致，页面更像是一个快照，函数组件中的state都被初始化了。 函数组件有一个输入框 值为5，再次进入时页面也显示5，但是打印出来的却是初始值。感觉真实dom与react虚拟dom不一致。

最近我们打算发一版，针对这个 issue 。

**Comment by GoodLuckAlien** [comment]
> 函数组件中，页面的状态与组件实际状态不一致，页面更像是一个快照，函数组件中的state都被初始化了。 函数组件有一个输入框 值为5，再次进入时页面也显示5，但是打印出来的却是初始值。感觉真实dom与react虚拟dom不一致。

方便提供一下代码片段吗？正常情况下，不会出现这个问题，因为被缓存的组件，在 keepalive 期间，是不会被销毁的
